name: Example GitHub Action

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:

      - name: 23f1002363@ds.study.iitm.ac.in
        run: echo "Hello, world!"
